
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOREQ = 25;
  public static final int PAR2 = 12;
  public static final int PAR1 = 11;
  public static final int MULT = 16;
  public static final int LLAVE2 = 31;
  public static final int EQUALS = 21;
  public static final int LLAVE1 = 30;
  public static final int ENTERO = 3;
  public static final int DOUBLE = 9;
  public static final int INT = 8;
  public static final int PRINTLN = 7;
  public static final int FOR = 32;
  public static final int FINCADENA = 6;
  public static final int IGUAL = 20;
  public static final int BOOL = 29;
  public static final int DIV = 17;
  public static final int NOEQUALS = 22;
  public static final int UMENOS = 15;
  public static final int IF = 28;
  public static final int ID = 5;
  public static final int EOF = 0;
  public static final int DECIMAL = 4;
  public static final int TRUE = 26;
  public static final int error = 1;
  public static final int CADENA = 2;
  public static final int DIF = 34;
  public static final int MENOS = 14;
  public static final int MENOR = 33;
  public static final int MOD = 18;
  public static final int BREAK = 35;
  public static final int MAYOR = 23;
  public static final int POTENCIA = 19;
  public static final int STRING = 10;
  public static final int FALSE = 27;
  public static final int MAYOREQ = 24;
  public static final int MAS = 13;
  public static final int CASA =36;
  public static final int BARRA =37;
  public static final int AMP =38;
  public static final int CHAR =39;
  public static final int MATCH =40;
  public static final int WHILE =41;
  public static final int DOWHILE =42;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "ID",
  "FINCADENA",
  "PRINTLN",
  "INT",
  "DOUBLE",
  "STRING",
  "PAR1",
  "PAR2",
  "MAS",
  "MENOS",
  "UMENOS",
  "MULT",
  "DIV",
  "MOD",
  "POTENCIA",
  "IGUAL",
  "EQUALS",
  "NOEQUALS",
  "MAYOR",
  "MAYOREQ",
  "MENOREQ",
  "TRUE",
  "FALSE",
  "IF",
  "BOOL",
  "LLAVE1",
  "LLAVE2",
  "FOR",
  "MENOR",
  "DIF",
  "BREAK",
  "CASA",
  "BARRA",
  "AMP",
  "CHAR",
  "MATCH",
  "WHILE",
  "DOWHILE"
  };
}

